name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  call-deploy:
    uses: christianbihasa/dev-toolkit/.github/workflows/deploy.yml@main
    with:
      build-path: './dist'